#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          custom:
#            client-id: spring-boot-oauth2-thymeleaf-app
#            client-secret: d3081cbf-6499-45c9-b579-9b1427d7c506
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/spring-boot-oauth2-thymeleaf-app
#        provider:
#          custom:
#            issuer-uri: http://localhost:9090/auth/realms/oauth2-demo-realm
#            jwk-set-uri: http://localhost:9090/auth/realms/oauth2-demo-realm/protocol/openid-connect/certs
#            user-name-attribute: preferred_username

keycloak:
  auth-server-url: http://localhost:9090/auth
  realm: oauth2-demo
  resource: spring-boot-oauth2-thymeleaf-app
  use-resource-role-mappings: true

management:
  endpoints:
    web:
      base-path: /api/manage
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: TRACE